apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{service-name}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{service-name}}.{{domain}}.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{service-name}}
          servicePort: 80